name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker

    steps:
      - name: Check docker
        run: docker ps

  runner-job:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: gradle/wrapper-validation-action@v1

      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build