name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker

    steps:
    - name: Check docker
      run: docker ps

  runner-job:
    runs-on: ubuntu-latest

    container: openjdk:8-alpine

    services:
      docker:
        image: docker

    steps:
    - uses: actions/checkout@master

    - name: Run tests
      run: ./gradlew test