name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker

    steps:
      - name: Check docker
        run: docker ps

  runner-job:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/wrapper-validation-action@v1

      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
      - name: Archive test results
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: build/reports/tests/test/index.html