name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
        architecture: x64

    - name: Check running directory
      run: pwd -P

    - name: Check gradle wrapper jar
      run: cd gradle/wrapper && ls

    - name: Run tests
      run: ./gradlew test